name: Auto Backup

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  # Allows manual triggering of the workflow
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Commit and push if changes
        run: |
          git add .
          timestamp=$(date -u)
          git commit -m "Auto backup: ${timestamp}" || echo "No changes to commit"
          git push 